name: Flutter CI Development

on:
  push:
    branches: [ master ]

jobs:
  build-and-test-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.0.9'
      - name: Cache Dart SDK
        uses: actions/cache@v2
        with:
          path: |
            ~/dartsdk
          key: ${{ runner.os }}-dart-sdk-v1-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-dart-sdk-v1-
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - uses: subosito/flutter-action@v1
        id: flutter
        with:
          flutter-version: '3.3.1'
      - name: Install dependencies
        run: flutter pub get
      - name: Run linting and static analysis
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Build APK for development
        run: flutter build apk --debug
      - name: Build iOS for development
        run: flutter build ios --debug
    # Add caching, handling .env files, and other necessary steps as needed
