name: Flutter CI Development

on:
  push:
    branches: [ master ]

jobs:
  build-and-test-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.0.9'

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Update PATH and Check Dart Version
        run: |
          echo "PATH=$(dirname $(which dart)):$PATH" >> $GITHUB_ENV
          dart --version

      - name: Print environment PATH
        run: echo $PATH

      - uses: subosito/flutter-action@v1
        id: flutter
        with:
          flutter-version: '3.3.1'

      - name: Check Bundled Dart SDK Version
        run: flutter doctor -v

      - name: Install dependencies
        run: |
          PATH=$(dirname $(which dart)):$PATH
          PATH=$(dirname $(which flutter)):$PATH
          flutter pub get

      - name: Run linting and static analysis
        run: |
          PATH=$(dirname $(which dart)):$PATH
          flutter analyze

      - name: Run tests
        run: |
          PATH=$(dirname $(which dart)):$PATH
          flutter test

      - name: Build APK for development
        run: |
          PATH=$(dirname $(which dart)):$PATH
          flutter build apk --debug

      - name: Build iOS for development
        run: |
          PATH=$(dirname $(which dart)):$PATH
          flutter build ios --debug
      # Add caching, handling .env files, and other necessary steps as needed
