name: ClosetConscious CI Trunk Based

on:
  push:
    branches: [ master ]

jobs:
  deploy_prod_ui:
    needs: deploy_prod_supabase
    name: prod_build
    runs-on: ubuntu-latest
    env:
      ENV: prod # Set the environment variable for production
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      WEB_CLIENT_ID: ${{ secrets.WEB_CLIENT_ID }}
      IOS_CLIENT_ID: ${{ secrets.IOS_CLIENT_ID }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.0.9'

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Update PATH and Check Dart Version
        run: |
          echo "PATH=$(dirname $(which dart)):$PATH" >> $GITHUB_ENV
          dart --version

      - name: Print environment PATH
        run: echo $PATH

      - uses: subosito/flutter-action@v1
        id: flutter
        with:
          flutter-version: '3.19.6'

      - name: Check Bundled Dart SDK Version
        run: flutter doctor -v

      - name: Create directory for keystore
        run: mkdir -p app

      - name: Decode and save production keystore file
        run: |
          echo "${{ secrets.PROD_KEYSTORE_BASE64 }}" | base64 --decode > app/prod_keystore.jks

      - name: Setup key.properties for production
        run: |
          echo "prodStoreFile=app/prod_keystore.jks" >> key.properties
          echo "prodStorePassword=${{ secrets.PROD_STORE_PASSWORD }}" >> key.properties
          echo "prodKeyAlias=${{ secrets.PROD_KEY_ALIAS }}" >> key.properties
          echo "prodKeyPassword=${{ secrets.PROD_KEY_PASSWORD }}" >> key.properties

      - name: Create app_config_prod.json
        run: |
          mkdir -p config
          echo '{
            "SUPABASE_URL": "'${{ secrets.SUPABASE_URL }}'",
            "SUPABASE_ANON_KEY": "'${{ secrets.SUPABASE_ANON_KEY }}'",
            "webClientId": "'${{ secrets.WEB_CLIENT_ID }}'",
            "iosClientId": "'${{ secrets.IOS_CLIENT_ID }}'"
          }' > config/app_config_prod.json

      - name: Install dependencies
        run: flutter pub get

      - name: Run linting and static analysis
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK for production
        run: flutter build apk --release --target=lib/main_prod.dart --dart-define=ENV=$ENV

      - name: Upload production APK
        uses: actions/upload-artifact@v2
        with:
          name: prod-apk
          path: build/app/outputs/flutter-apk/app-release.apk