name: Flutter CI Development

on:
  push:
    branches: [ master ]

jobs:
  build-and-test-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.0.9'

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Update PATH and Check Dart Version
        run: |
          echo "PATH=$(dirname $(which dart)):$PATH" >> $GITHUB_ENV
          dart --version

      - name: Print environment PATH
        run: echo $PATH

      - uses: subosito/flutter-action@v1
        id: flutter
        with:
          flutter-version: '3.19.6'

      - name: Check Bundled Dart SDK Version
        run: flutter doctor -v

      - name: Create .env file
        run: |
          echo "IOS_CLIENT_ID=${{ secrets.IOS_CLIENT_ID }}" >> .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "WEB_CLIENT_ID=${{ secrets.WEB_CLIENT_ID }}" >> .env

      - name: Install dependencies
        run: flutter pub get

      - name: Run linting and static analysis
        run: flutter analyze --verbose

      - name: Run tests
        run: flutter test

      - name: Build APK for development
        run: flutter build apk --debug

      - name: Build iOS for development
        run: flutter build ios --debug
